### ISSUE TITLE
Broken ZVV API

### ISSUE THREAD

**Issue by amuelli** [timeforcoffee/tramboard-clj#12]
It seems that the ZVV API used no longer responds in JSON.

The implementation of the ZVV website currently uses a POST to http://online.fahrplan.zvv.ch/bin/stboard.exe/dny. (GET is also accepted)

An example for the next 10 journeys from Oerlikon:
http://online.fahrplan.zvv.ch/bin/stboard.exe/dny?input=8503006&dirInput=&maxJourneys=10&boardType=dep&start=1&tpl=stbResult2json

This returns JSON, however in a different structure than before.

**Comment by fterrier** [comment]
Thanks for that! I'll have a look

**Comment by fterrier** [comment]
I changed to that API. Noticed there is a lot more info there than before (stations along the line, infos on disturbances) so maybe we could use that somehow.
