### ISSUE TITLE
increase cell width

### ISSUE THREAD

**Issue by mruoss** [timeforcoffee/tramboard-clj#7]
![whylikethis](https://cloud.githubusercontent.com/assets/695307/6752313/a5031584-cf0d-11e4-805d-ae3b8859a881.png)

**Comment by fterrier** [comment]
which browser was that ? on which device ?

**Comment by mruoss** [comment]
Chrome on a thinkpad s420. ;b
Ubuntu.
Am 05.04.2015 00:17 schrieb "François Terrier" <notifications@github.com>:
